replicaCount: 1

image:
  pullPolicy: IfNotPresent
  registry: ghcr.io
  registrySecretName: datamesh-manager-registry # create secret beforehand
  name: ghcr.io/datamesh-manager/datamesh-manager-enterprise
  tag: 1.4.11

datameshmanager:
  host: "https://datamesh-manager.example.com"

database:
  url: jdbc:postgresql://localhost:5432/postgres # change to your database URL
  secretName: datamesh-manager-database # create secret beforehand
  usernameKey: username
  passwordKey: password

smtp:
  host: smtp.example.com
  port: "1025"
  secretName: datamesh-manager-smtp # create secret beforehand
  usernameKey: username
  passwordKey: password

sso:
  azure:
    enabled: false
    issuerUri: "https://login.microsoftonline.com/cc62cfd7-babf-43fa-89c8-000000000000/v2.0"
    secretName: datamesh-manager-azure-sso # create secret beforehand
    clientIdKey: client-id
    clientSecretKey: client-secret

# Additional environment variables to be set in the deployment
# Format:
# env:
#   - name: VARIABLE_NAME
#     value: "variable-value"
env: []

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 1
    memory: 2Gi

startupProbe:
  httpGet:
    path: /login
    port: 8080
  failureThreshold: 30
  periodSeconds: 10
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  httpGet:
    path: /login
    port: 8080
readinessProbe:
  httpGet:
    path: /login
    port: 8080

nodeSelector: {}

tolerations: []

affinity: {}